### ISSUE TITLE
Cant download 1440p60 quality video

### ISSUE THREAD

**Issue by dmkenza** [glubsy/livestream_saver#10]
I try to download stream and i got 1080p, in despite of the video has 1440p resolution max. 

What is the problem? Is it possible to download better than 1080p ? Is it stricts of youtube or programm cant download?

If it need for debug: I'm downloading streams from this youtuber. He is removing his streams always.
https://www.youtube.com/channel/UC1XLQIzXJd_KaLOuEVFESVw

**Comment by glubsy** [comment]
I'm looking into it, thanks for the report.

**Comment by glubsy** [comment]
This is fixed by commit 96618bf09ab13fdc9847f8f7e0a1917e673ab935
