### ISSUE TITLE
Syntax Error when monitoring a channel

### ISSUE THREAD

**Issue by kalker-3** [glubsy/livestream_saver#18]
Hi there.

I followed the installation instructions and made a virtual environment, the dependencies also installed correctly, but when I launch the script using `python livestream_saver.py monitor CHANNEL_URL` I get the following error:

```  
File "livestream_saver.py", line 400
    if level := config.get(mode_str, "log_level", vars=args):
              ^
SyntaxError: invalid syntax
```

This is with Python 3.7.3

**Comment by glubsy** [comment]
You need python 3.8. The ":=" (aka "walrus) operator did not exist before that version.

If you cannot upgrade python, you could change the code for this type of error to something like

```python3
level = config.get(mode_str, "log_level", vars=args)
if level:
    ...
```

**Comment by kalker-3** [comment]
That worked, updated to 3.9.6 and it's downloading just fine now.

Thanks for the help. :)
