### ISSUE TITLE
Monitoring always return empty lists

### ISSUE THREAD

**Issue by nukezzz** [glubsy/livestream_saver#19]
Returned lists of "Currently listed public videos" and "Currently listed community videos" are always empty for any channels I tried.

**Comment by Arayn** [comment]
Are you using cookies?

**Comment by glubsy** [comment]
Can you give an example channel? What operating system and Python version do you use? What is the output in terminal emulator?

**Comment by nukezzz** [comment]
Weird. Today everything works fine.
