### ISSUE TITLE
Fails to run on windows (setsid)

### ISSUE THREAD

**Issue by 123HD123** [glubsy/livestream_saver#23]
It failed to run on windows for me because the import `from os import setsid` doesn't exist. Simply removing that specific import makes it work fine with downloading and merging but it probably breaks something on another os?

Edit: It's imported in the main file but has no use there and it gets imported in the hooks.py file and used as `preexec_fn=setsid`

**Comment by glubsy** [comment]
Thanks for the report. This should be fixed by ea74d19f18bf290fe657d117ab7d4ecc45f673db.
