### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by young-hnau** [glubsy/livestream_saver#24]
This looks like an awesome project and one I would love to run on my server. The easiest way to do that is with a docker. Any chance you could create one?

**Comment by glubsy** [comment]
I have very little experience with Docker in general, so I can't give you an ETA, but it's definitely on my roadmap.

I want to finish rewriting a few things with asyncio first, then I'll work on that.

**Comment by Yash2737** [comment]
can I pick this up ? @glubsy

**Comment by glubsy** [comment]
@Yash2737 sure do whatever. I have had no time to work on this project lately but I plan on coming back to it eventually.

There is already a [pull request on this topic](https://github.com/glubsy/livestream_saver/pull/34) you might want to have a look at it.

**Comment by glubsy** [comment]
Docker support added in https://github.com/glubsy/livestream_saver/pull/79

Also uploaded an image (based on Debian, might be a bit big) here: https://hub.docker.com/r/glubsy/livestream_saver
