### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by gskvhfk** [glubsy/livestream_saver#25]
I don't how to use ur code
please say me how to do it from first 
I could not download my YouTube classes because it made private after class please help

**Comment by glubsy** [comment]
Check the [Readme.md file](https://github.com/glubsy/livestream_saver#installation).

You simply need to have Python3 installed on your system. Then follow the instructions, and start the program as shown in the examples (look for "Basic usage" lines). 

For example, let's say you want to monitor a channel and download any active live stream in maximum quality, type into your preferred terminal emulator:
`python livestream_saver.py monitor "https://www.youtube.com/channel/UCtxCXg-UvSnTKPOzLH4wJaQ"`

I'm afraid I can't help you any more than that.

If you are attempting to download videos which have already been made private, there is nothing we can do about it.

**Comment by gskvhfk** [comment]
bro i installed it can u send syntax for merging with example and 
download video with resolution with one example

**Comment by glubsy** [comment]
To download with a maximum video height resolution of 360p: `livestream_saver.py [download|monitor] -q 360 ...`.

To merge: `livestream_saver.py merge /path/to/stream_capture_XXXXXXXXXXX`.
