### ISSUE TITLE
ImportError: cannot import name 'wait' from 'os'

### ISSUE THREAD

**Issue by pommidorka** [glubsy/livestream_saver#28]
Hey! In Windows 10, when trying to download a stream, the following error occurred:

`Traceback (most recent call last):
  File "E:\STREAMS\youtube_stream_capture\livestream_saver-main\livestream_saver.py", line 12, in <module>
    from livestream_saver.download import YoutubeLiveStream
  File "E:\STREAMS\youtube_stream_capture\livestream_saver-main\livestream_saver\download.py", line 2, in <module>
    from os import sep, path, makedirs, listdir, wait
ImportError: cannot import name 'wait' from 'os' (C:\Users\User\AppData\Local\Programs\Python\Python310\lib\os.py)`

Fixed by replacing the second line in livestream_saver\download.py with:
`from os import sep, path, makedirs, listdir`

"wait" is not used there by the way

**Comment by glubsy** [comment]
Thanks for reporting.
