### ISSUE TITLE
Add webhook notification

### ISSUE THREAD

**Issue by Ryu1845** [glubsy/livestream_saver#30]
Hello, I've seen your project and I think it could be quite useful to me and some of my friends. However I was wondering if it would be possible to add webhook support as an alternative to email notifications. We use Discord a lot and it's seems like the perfect way to notify our community.

I may be able to submit a pull request with the corresponding code if I have the time and you allow it.

**Comment by glubsy** [comment]
You can already call webhooks by calling your own external scripts on each defined event (see the config file template). However, the events still lack some variables / placeholders right now, but let me know if you have specific values you'd like to see replaced in the commands. Right now there is only %VIDEO_ID% and %COOKIE_PATH% but we can add a lot more.

Anyway I think that's a good idea to have support for webhooks directly inside the program. 
The tricky part is to make a generic interface to support various webhook APIs, all the while allowing easy customization by the user. 
I can work out a quick and simple solution but feel free to submit patches if you have something more specific in mind.
I'm thinking of having the payload JSON in the config file, and the API endpoint URL (with the authentication tokens) could be in both the config file and environment variables. Would that be enough? 

What kind of information would you like to send? My guess: upcoming video detected, video added to channel, live stream started (and the corresponding metadata).

**Comment by Ryu1845** [comment]
That sounds perfect thank you. It's mostly live stream started, yeah. Useful variables would be channel name, title, also date maybe.

**Comment by glubsy** [comment]
Added rudimentary webhook support in 187f9a451a617.
Here is an example of what you can achieve on Discord with the current implementation of hooks:
![2021-12-23_20-56-15](https://user-images.githubusercontent.com/12895548/147290492-76978797-f836-4075-9d71-22ac778cc150.png)

There might be bugs, so if you spot anything weird please let me know. I'll try to polish this a bit more later when I have some time.

**Comment by Ryu1845** [comment]
Thank you and merry Christmas! I'll try this out later this week hopefully.
