### ISSUE TITLE
[feature request] Computer shut down after a stream is over

### ISSUE THREAD

**Issue by turbodude** [glubsy/livestream_saver#31]
Please add if possible. Or a suggestion on how this could be implemented in Windows would be appreciated 🙏

**Comment by glubsy** [comment]
You can already achieve that by calling your own scripts on event hooks. In this case you could use `on_merge_done_command`. 

But currently this will only work if the merge has been successful. I should improve things on that side ASAP.

**Comment by glubsy** [comment]
This can be achieve with wrapper scripts.
