### ISSUE TITLE
[feature request] Monitor Membership tab for streams not attached to posts

### ISSUE THREAD

**Issue by richardd89** [glubsy/livestream_saver#46]
Not sure if this is a recent change on Youtube, but one channel that I have set for monitoring has recently posted some members-only streams that were not attached to any Community posts. Because of this, they do not show up in the Community tab at all, but do show up in the Membership tab as just a video/stream entry (like the kind you see if you scroll down any Membership tab for a bit). Due to this, the channel monitoring function was not able to see the streams to automatically download them.

I double checked to make sure it wasn't a cookie issue by replacing my cookie file, and I also still see older member-only streams (that are attached to Community posts) listed in the "Currently listed community videos" list. Also, if I use the plain Download function and manually specify the member-only video URL, the stream is seen and downloads fine.

From what I'm gathering, it seems a new function to monitor the Membership tab for new streams (not just ones attached to posts) might be needed to cover these cases.

**Comment by glubsy** [comment]
Thanks for the heads up. Indeed this is a very recent change on Youtube's side, I will have to adapt the code to monitor the  membership tab as well.

**Comment by glubsy** [comment]
This should now be fixed by dbac6bfdee4fa7b24486abf34e7751c94ef240fa. I have not fully tested yet but from preliminary checks it lists the videos posted on the membership tab just fine. 
Feel free to re-open if you encounter more issues related to membership streams.

**Comment by richardd89** [comment]
Thanks for the update! I now see that it's monitoring Membership streams, but the ones that are showing on the monitor list are only ones that were previously attached to member-only posts, not seeing the ones that were "standalone". I'll keep an eye on the next time there is a member-only stream to see if the monitor picks them up anyway.

**Comment by glubsy** [comment]
Heads up, there was a bug that previously resulted in only videos attached to posts being collected. This should be fixed now by e6d0199, all videos from the membership tab should be collected.

**Comment by richardd89** [comment]
Confirmed, I see them listed now, thanks!
