### ISSUE TITLE
Missing Videos tab endpoint data for Livestream VODS

### ISSUE THREAD

**Issue by rrgodhorus** [glubsy/livestream_saver#51]
Looks like Youtube has added a new tab (LIVE) to store Livestream VODs....If the channel does not have any non live stream VOD videos, an exception is thrown in monitor.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/29102444/199208437-4923719a-13d8-483d-8cc4-d2b3d497b877.png">

**Comment by glubsy** [comment]
Thanks for reporting, this should now be fixed by 7a0cf1d2a6aea462bf149e08bec1627d6b820572

**Comment by rrgodhorus** [comment]
Thanks for the quick fix!
