### ISSUE TITLE
 Could not find ffmpeg or ffprobe.

### ISSUE THREAD

**Issue by araza4047** [glubsy/livestream_saver#59]
There is an exception which states that "Exception: Could not find ffmpeg or ffprobe! Make sure it is installed and discoverable from your PATH environment variable". Due to which merge is not working
![git1](https://user-images.githubusercontent.com/27481271/211534931-16a15494-2e11-4023-ad20-3e98c2e18d65.PNG)

**Comment by glubsy** [comment]
ffmpeg (and ffprobe) are listed as dependencies in the Readme file.
Simply install ffmpeg and make sure they can be started from the command line (if you install it with a package manager that should work automatically ).
