### ISSUE TITLE
Unhandled exception: Missing streamingData key in json causing downloads to be interrupted

### ISSUE THREAD

**Issue by rrgodhorus** [glubsy/livestream_saver#60]
I've noticed this issue multiple times while downloading long streams recently. The download fails and goes back to monitoring.
PFA the relevant screenshot with the error.

<img width="1792" alt="Screenshot 2023-03-13 at 9 35 17 AM" src="https://user-images.githubusercontent.com/29102444/224906301-e722fe2b-a355-4c06-9f3b-f43ff4d08d90.png">

**Comment by N1ck01** [comment]
I've been experiencing the same error as well recently. I've tried both the new @channel names and the old channel IDs with the same results, but I believe the error has also occurred with direct video links too...
I sure hope the dev here is still willing and able to work on this tool.

**Comment by glubsy** [comment]
Yes I have noticed this too, I'm investigating how to handle that better.

@rrgodhorus it might be best to copy the log (preferrably with debug log level) instead of a screenshot. Just be wary of potential information leak when pasting (although nothing too sensitive should be in there);

**Comment by glubsy** [comment]
This should be fixed by a59fc85a3f745cfd3439cffeac755544c1bccf4a. 

Pytube is becoming more and more unreliable so we fallback to getting stream descriptors from the MPD.

**Comment by rrgodhorus** [comment]
Thanks!
