### ISSUE TITLE
I think the latest change broke something

### ISSUE THREAD

**Issue by mechalincoln** [glubsy/livestream_saver#62]
![livestream_saver_issue_2](https://user-images.githubusercontent.com/49933679/226142554-6cf35a07-5e20-4259-80f2-e97befed2d92.PNG)
Currently it's reading the channel but ignoring the livestream itself.

The command I used was

`python3 livestream_saver.py monitor -c livestream_saver.cfg https://www.youtube.com/c/DuncanAndFriendsPranks/videos
`

Before the recent change it was working fine most of the time.

I have the variance set to 0.000000001 so that's why it is checking so often. I had that setting before the recent change and it worked fine, so it isn't a result of that,

Regardless, I am thankful for your updates to this program, which when it works has proven to be invaluable.

**Comment by glubsy** [comment]
Thanks for reporting. If you run the program with a debug log level, you'll notice an error coming from pytube. 
If you are in a hurry you could refer to [this thread](https://github.com/pytube/pytube/issues/1498) and change the code in pytube directly. 

Most likely related to https://github.com/glubsy/livestream_saver/issues/61 (I'm currently working on a fix)

**Comment by glubsy** [comment]
This is hopefully fixed by https://github.com/glubsy/livestream_saver/commit/36dbcf82b89530aed64964a29ea651a8e86cc20b
