### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by qo4on** [glubsy/livestream_saver#65]
How do I get cookie?
I created a `cookie.txt` file with the content of the YouTube page cookie request header in my browser and I see `Failed to load cookie file`.

**Comment by glubsy** [comment]
If you use Chromium based browsers, you could use [this method](https://github.com/dandv/convert-chrome-cookies-to-netscape-format). If you use Firefox based browsers, you could use [this addon](https://github.com/hrdl-github/cookies-txt). I'll add these to the Readme file.

**Comment by glubsy** [comment]
Note that currently everything is broken and using cookies will not improve anything until I get around to implement a fix.
