### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jtheletter** [glubsy/livestream_saver#68]
The readme says to run `python3 -m pip install -r requirements.txt`. That outputs: `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`.

**Comment by timrhaynes** [comment]
Did you clone the repo and run that command from within the clone folder?

**Comment by jtheletter** [comment]
I did not. That is not included in the instructions.

**Comment by glubsy** [comment]
Thanks for pointing it out, I updated the installation instructions in the Readme.
