### ISSUE TITLE
Quality is not highest by default

### ISSUE THREAD

**Issue by MaxMls** [glubsy/livestream_saver#72]
All downloaded video streams are in 640x360 resolution, even those that are available in 1440p.

**Comment by glubsy** [comment]
Indeed, this is because we use a temporary workaround to download. 

You have to edit the [yt_dlp.conf](https://github.com/glubsy/livestream_saver/blob/main/yt_dlp_conf.py) file to accomodate what you want to pass to yt-dlp. For example:

```python
'format': 'mp4+m4a/bestvideo+bestaudio',
```

**Comment by glubsy** [comment]
Default should be highest quality (but still forced selection to mp4+aac).
