### ISSUE TITLE
[Question] How to make the "livestream_saver" download videos in monitor mode without splitting the downloaded video file into parts?

### ISSUE THREAD

**Issue by JunioCalu** [glubsy/livestream_saver#73]
How to make the "livestream_saver" download videos in monitor mode without splitting the downloaded video file into parts?

**Comment by glubsy** [comment]
There is no way right now. Feel free to submit a patch though.

The reason behind this design choice was to allow for redownloading a chunk that failed to download the first time, and avoid having a corrupt merged file at the end of the download process.

**Comment by JunioCalu** [comment]
I took this issue to the yt-dlp maintainers. The "--live-from-start" parameter causes fragmentation. But one of the maintainers said that it is not possible to download a video file from a live starting from the beginning without fragmenting, when this parameter is used.

Link from a maintainer's answer:
https://github.com/yt-dlp/yt-dlp/issues/7865

**Comment by JunioCalu** [comment]
> I probably misunderstood your question, I thought this was related to the previous way we downloaded streams (with our native download methods) not the yt-dlp's way. Not much I can do when it comes to yt-dlp.

The native way and the way yt-dlp works are very similar.
