### ISSUE TITLE
The function "get_public_streams" from the monitor.py file returns random VOD's after a certain time.

### ISSUE THREAD

**Issue by JunioCalu** [glubsy/livestream_saver#77]
After some time of monitoring the channel the livestream_saver starts to recognize old random VOD's as new VOD's and downloads them.

**Comment by glubsy** [comment]
I have never seen that happen so I might need some example. I am surprised it would even download VODs, it is not supposed to be able to do that. 

Might be a side effect of using yt-dlp as a downloader... need some investigation.

**Comment by JunioCalu** [comment]
> Might be a side effect of using yt-dlp as a downloader... need some investigation.

I suppose that the line `self.trigger_hook('on_video_detected', vid)` after `continue` is capturing random videos, but this must be a problem in the mechanism that requests the list of videos from the monitored channel at each repeat loop, It may be that the function responsible for requesting the list is not managing to request a complete list of videos from the "public streams" session of the monitored channel.

```
                for vid in new_comm_videos:
                    if vid.get("upcoming"):
                        self.trigger_hook('on_upcoming_detected', vid)
                    if vid.get("isLiveNow") or vid.get("isLive"):
                        continue
                    # Although rare, this should trigger for VODs only
                    self.trigger_hook('on_video_detected', vid)
```

**Comment by glubsy** [comment]
Closing as I have not seen this happening and the code has changed since then which may have fixed the issue. Feel free to reopen if this is still occurring.
