### ISSUE TITLE
Video and Audio files  are not combined at end of stream

### ISSUE THREAD

**Issue by timrhaynes** [glubsy/livestream_saver#80]
For a while now, livestream_saver doesn't properly merge the video and audio files after recording a stream. This is on a brand new, fully updated raspbian installation with nothing added but livestream_saver.

Logfile with channel and show name scrubbed, is attached. Hopefully it helps in diagnosing the issue. I can provide the channel name if you want to test monitoring it.

[output.log](https://github.com/glubsy/livestream_saver/files/14548882/output.log)

**Comment by glubsy** [comment]
Thanks for reporting! This error comes from yt-dlp during the post-processing phase. Nothing I can do about it, you should report it to the [yt-dlp issue tracker](https://github.com/yt-dlp/yt-dlp/issues).

Make sure you are using the latest version of yt-dlp at all times. If you run livestream_saver in a virtual env, you'll have to upgrade the version installed in the virtual environment:
```sh
source /path/to/venv/bin/activate
pip install --upgrade yt-dlp
```

I'm sure you'll find similar issue on the yt-dlp issue tracker. If your files were not merged at all, you can use ffmpeg to do it manually. Something along the lines of:
```sh
ffmpeg -i video.mp4 -i audio.m4a -c copy output.mp4
```
