### ISSUE TITLE
-q parameter ignored?

### ISSUE THREAD

**Issue by timrhaynes** [glubsy/livestream_saver#81]
Monitoring a channel with format option:
-q "720"
but downloaded videos area always in 1920 vertical resolution.

Should I hardcode the format in the ytdlp_config.json instead?

**Comment by glubsy** [comment]
Yes, this parameter is ignored currently. As you stated, you have to edit the ytdlp_config.json file to pass your arguments to ytdlp.
Sorry for the confusion.
